SELECT
FROM ORDERS O
WHERE 
    O.PURCHASE_AMT = (
        SELECT MAX(PURCHASE_AMT)
        FROM ORDERS
        WHERE ORD_DATE = O.ORD_DATE 
    )

SELECT S.SALESMAN_ID, S.NAME
FROM SALESMAN S
JOIN CUSTOMER C ON C.SALESMAN_ID = S.SALESMAN_ID
HAVING COUNT(C.CUSTOMER_ID) > 1
GROUP BY S.SALESMAN_ID, S.NAME;